config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  # see all pets
  get '/pets', to: 'pets#index', as: :pets

  post '/pets', to: 'pets#create'

  get '/pets/new', to: 'pets#new', as: :new_pet

  get '/pets/:id', to: 'pets#show', as: :pet

  get '/pets/:id/edit', to: 'pets#edit', as: :edit_pet

  patch '/pets/:id', to: 'pets#update'

  delete '/pets/:id', to: 'pets#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = [ 'dog', 'cat', 'turtle', 'bird', 'hamster' ]

  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    # FIND THE RIGHT PET
    @pet = Pet.find(params[:id])
  end

  def new
    # create the empty instance
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    # raise
    @pet.save

    redirect_to pets_path
  end

  def edit
    # Find the right instance
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet.id) #=> /pets/623542
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    redirect_to pets_path, status: :see_other
  end

  private

  # STRONG PARAMS
  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Lost Kitty 1753" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%# IN PARTIALS WE MUST NOT HAVE  %>
<%#  INSTANCE VARIABLES! %>

<%# HTML COMPONENTS %>

<%#= form_with(model: pet) do |f| %>
  <%#= f.label :name %>
  <%#= f.text_field :name %>
  <%#= f.label :address %>
  <%#= f.text_field :address %>
  <%#= f.label :species %>
  <%#= f.select :species, Pet::SPECIES %>
  <%#= f.label :found_on %>
  <%#= f.date_field :found_on %>
  <%#= f.submit %>
<%# end %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
        <%= simple_form_for(pet) do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :species, collection: Pet::SPECIES %>
          <%= f.input :found_on %>
        <% end %>
    </div>
  </div>
</div>

app/views/pets/edit.html.erb
<h1>Edit <%= @pet.name %></h1>

<%# PARTIALS %>
<%= render 'form', { pet: @pet } %>

app/views/pets/index.html.erb
<h1>Found pets</h1>

<ul>
  <% @pets.each do |pet| %>
    <li><%= link_to pet.name, pet_path(pet.id) %> <%= link_to 'Remove', pet_path(pet.id), data: { turbo_method: :delete, turbo_confirm: 'WHY?!?!?!?!'} %></li>
  <% end %>
</ul>

<%= link_to 'Report pet', new_pet_path, class: 'btn btn-primary' %>

app/views/pets/new.html.erb
<h1>Report pet</h1>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>

<p>Address: <%= @pet.address %></p>
<p>Species: <%= @pet.species %></p>
<p>Found on: <%= @pet.found_on %></p>

<%= link_to 'See all', pets_path %> |
<%= link_to "edit #{@pet.name}", edit_pet_path(@pet.id) %>